[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  # Allowlisting non-secret client keys that are expected in the build output
  # Firebase Web API keys are public and safe to expose per Firebase docs
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID,VITE_FIREBASE_API_KEY"

# Environment variables will be set in Netlify's dashboard
# Required environment variables:
# - OPENAI_API_KEY 