[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Environment variables will be set in Netlify's dashboard
# Required environment variables:
# - OPENAI_API_KEY 